### ISSUE TITLE
rake gettext:store_<form/policy>_attributes error

### ISSUE THREAD

**Issue by Djurredejong** [nedap/railjet#30]
```writing form translations to: /home/djurre.dejong/src/Behandel-Ons/locale/form_attributes.rb
[Error] Attribute extraction failed. Removing incomplete file (/home/djurre.dejong/src/Behandel-Ons/locale/form_attributes.rb)
rake aborted!
NoMethodError: undefined method `attribute_set' for #<Class:XPath::HTML>
```

The ```GettextI18n::TranslateAttributes::AttributeFinder.objects``` also includes ```XPath::HTML```. For some reason ```XPath::HTML == Railjet::Policy```.

Changing the code to 
``` def objects
        @objects ||= ObjectSpace.each_object(Class).select do |c|
          c.included_modules.include?(base_class) && !c.included_modules.include?(XPath::HTML)
        end
     end
```
does fix the problem. But understanding why it happens would be better.

**Comment by zlw** [comment]
Caused by having xpath gem (capybara dependency) available in development environment. 
Fixed by moving dependency to test group in Gemfile
